name: Build and upload plugin

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds and uploads the plugin executable file to Aliyun OSS
  build-and-upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up Go environment
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      
      # Builds the plugin executable file
      - name: Build plugin
        run: go build -o plugin main.go
      
      # Installs and configures ossutil
      - name: Install ossutil
        run: |
          mkdir -p "$HOME/.local/bin"
          wget -O "$HOME/.local/bin/ossutil" https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
          chmod +x "$HOME/.local/bin/ossutil"
          "$HOME/.local/bin/ossutil" config --endpoint=$OSS_ENDPOINT --access-key-id=$OSS_ACCESSKEY_ID --access-key-secret=$OSS_ACCESSKEY_SECRET
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        env:
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_ACCESSKEY_ID: ${{ secrets.OSS_ACCESSKEY_ID }}
          OSS_ACCESSKEY_SECRET: ${{ secrets.OSS_ACCESSKEY_SECRET }}
      
      # Uploads the plugin executable file to Aliyun OSS
      - name: Upload plugin
        run: ossutil cp plugin oss://my-bucket/my-path/plugin --update --force
